packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true
autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false
dedupePeerDependents: false
onlyBuiltDependencies:
  - esbuild

syncInjectedDepsAfterScripts:
  - build
