import type { Metadata } from 'next';
import AnonymousUserManager from '../components/AnonymousUserManager';
import { AuthProvider } from '../lib/auth/AuthContext';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body className="antialiased">
        <AuthProvider>
          <AnonymousUserManager />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
