import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '../lib/auth/AuthContext';
import AnonymousUserManager from '../components/AnonymousUserManager';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className="antialiased"
      >
        <AuthProvider>
          <AnonymousUserManager />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
