import {
  AttributeType,
  ModifierType,
} from '@shared/engine/battle-v5/core/types';
import type { SectDefinitionWithoutPaths } from '../../core';
import { LINGXIAO_SECT_ID } from './ids';

export const LINGXIAO_BASE_DEFINITION: SectDefinitionWithoutPaths = {
  id: LINGXIAO_SECT_ID,
  name: '凌霄剑宗',
  description: '拜山问剑，研习六卷心法，于快剑、重剑二道中自定剑途。',
  trial: {
    name: '入门试剑',
    description: '借宗门法器体验基础传承，胜负皆记作完成。',
  },
  raceIds: ['human'],
  configVersion: 4,
  combatResource: {
    id: 'sect.lingxiao.sword-momentum',
    name: '剑势',
    icon: '🗡️',
    max: 6,
  },
  methods: [
    {
      id: 'lingxiao-canon',
      slot: 1,
      name: '《问剑篇》',
      isPrimary: true,
      description:
        '凌霄历代剑修将平生问剑之悟尽录于此；六卷同源，诸般剑诀皆由一问而生。',
      perLevelDescription: '限制各基础分卷可研习的最高等级。',
    },
    {
      id: 'sword-guidance',
      slot: 3,
      name: '《剑气凌霄》',
      description: '养胸中一口凌霄剑气，聚则锋芒内敛，发则长空为之开阖。',
      perLevelDescription: '每级提高0.05%物理攻击。',
      modifierPerLevel: {
        attrType: AttributeType.ATK,
        type: ModifierType.ADD,
        value: 0.0005,
      },
    },
    {
      id: 'void-step',
      slot: 4,
      name: '《凌虚步》',
      description: '御气踏虚，借天地微风而行；心念所至，身影已越剑锋之外。',
      perLevelDescription: '每级提高0.02个百分点闪避率。',
      modifierPerLevel: {
        attrType: AttributeType.EVASION_RATE,
        type: ModifierType.FIXED,
        value: 0.0002,
      },
    },
    {
      id: 'edge-cleansing',
      slot: 2,
      name: '《观微剑意》',
      description: '静观一息之变，明察毫厘之机；敌势未成，破绽已映于剑心。',
      perLevelDescription: '每级提高0.02个百分点命中。',
      modifierPerLevel: {
        attrType: AttributeType.ACCURACY,
        type: ModifierType.FIXED,
        value: 0.0002,
      },
    },
    {
      id: 'origin-returning',
      slot: 5,
      name: '《万法不侵》',
      description: '澄心定意，以剑守神；任外法纷至，灵台自明，不为所动。',
      perLevelDescription: '每级提高0.05%法术防御。',
      modifierPerLevel: {
        attrType: AttributeType.MAGIC_DEF,
        type: ModifierType.ADD,
        value: 0.0005,
      },
    },
    {
      id: 'sword-nurturing',
      slot: 6,
      name: '《不灭剑体》',
      description: '以身作剑，以骨为脊，经千锤百炼而锋芒不折、形神不摧。',
      perLevelDescription: '每级提高0.05%物理防御。',
      modifierPerLevel: {
        attrType: AttributeType.DEF,
        type: ModifierType.ADD,
        value: 0.0005,
      },
    },
  ],
  abilities: [
    {
      id: 'plain-sword',
      methodId: 'lingxiao-canon',
      baseName: '基础剑式',
      description: '一招一式皆循剑理，平实之中自有万般变化。',
      unlockLevel: 1,
      occupiesActiveSlot: false,
      role: 'generator',
      manaWeight: 0,
      cooldown: 0,
    },
    {
      id: 'sect-ultimate',
      methodId: 'lingxiao-canon',
      baseName: '剑破万法',
      description: '一剑既出，诸法皆寂；万般玄妙，尽断于锋芒之前。',
      unlockLevel: 10,
      occupiesActiveSlot: true,
      role: 'finisher',
      manaWeight: 2.5,
      cooldown: 4,
    },
    {
      id: 'guiding-sword',
      methodId: 'sword-guidance',
      baseName: '剑起沧澜',
      description: '剑意初起如沧海生澜，一重未歇，一重又至。',
      unlockLevel: 1,
      occupiesActiveSlot: true,
      role: 'generator',
      manaWeight: 1,
      cooldown: 0,
    },
    {
      id: 'linked-edge',
      methodId: 'sword-guidance',
      baseName: '剑荡山河',
      description: '剑锋纵横，如长河奔涌；所过之处，山河亦为之震荡。',
      unlockLevel: 5,
      occupiesActiveSlot: true,
      role: 'combo',
      manaWeight: 1.5,
      cooldown: 2,
    },
    {
      id: 'turning-body',
      methodId: 'void-step',
      baseName: '藏锋听雷',
      description: '锋芒藏于静处，杀机伏于未发；剑出之时，恰似平地惊雷。',
      unlockLevel: 3,
      occupiesActiveSlot: true,
      role: 'defensive',
      manaWeight: 1.25,
      cooldown: 3,
    },
    {
      id: 'shadow-step',
      methodId: 'void-step',
      baseName: '踏雪无痕',
      description: '身随剑走，来去无迹；踏雪而过，不留半点尘痕。',
      unlockLevel: 5,
      occupiesActiveSlot: true,
      role: 'generator',
      manaWeight: 1,
      cooldown: 4,
    },
    {
      id: 'breaking-edge',
      methodId: 'edge-cleansing',
      baseName: '一剑破妄',
      description: '照见虚实，勘破迷障；一剑所向，诸般妄法无所遁形。',
      unlockLevel: 3,
      occupiesActiveSlot: true,
      role: 'utility',
      manaWeight: 1.5,
      cooldown: 3,
    },
    {
      id: 'sword-aegis',
      methodId: 'origin-returning',
      baseName: '剑心通明',
      description: '剑心澄澈，如明镜照世；万法临身，自见其隙。',
      unlockLevel: 3,
      occupiesActiveSlot: true,
      role: 'defensive',
      manaWeight: 1.25,
      cooldown: 5,
    },
    {
      id: 'nurturing-sword',
      methodId: 'sword-nurturing',
      baseName: '人剑合一',
      description: '心与剑合，意与气通；人即是剑，剑亦由心。',
      unlockLevel: 3,
      occupiesActiveSlot: true,
      role: 'defensive',
      manaWeight: 1.5,
      cooldown: 5,
    },
  ],
  onboarding: {
    initialContribution: 30,
    initialMethods: {
      'lingxiao-canon': 5,
      'sword-guidance': 1,
      'void-step': 1,
      'edge-cleansing': 1,
      'origin-returning': 1,
      'sword-nurturing': 1,
    },
    initialAbilityLoadout: ['guiding-sword', null, null, null],
  },
};
