import {
  AttributeType,
  ModifierType,
} from '@shared/engine/battle-v5/core/types';
import type { PlayerRaceDefinition, SectDefinition } from '../../types';
import { LINGXIAO_SECT_ID } from './ids';

export const HUMAN_RACE: PlayerRaceDefinition = {
  id: 'human',
  name: '人族',
  description: '生于尘世而善悟百法，诸道皆可问、诸门皆可入。',
};
export const LINGXIAO_BASE_DEFINITION: Omit<SectDefinition, 'paths'> = {
  id: LINGXIAO_SECT_ID,
  name: '凌霄剑宗',
  description: '拜山问剑，研习六卷心法，于快重二道中自定剑途。',
  trial: {
    name: '入门试剑',
    description: '借宗门法器体验基础传承，胜负皆记作完成。',
  },
  raceIds: ['human'],
  configVersion: 2,
  methods: [
    {
      id: 'lingxiao-canon',
      slot: 1,
      name: '《凌霄剑典》',
      isPrimary: true,
      description: '凌霄剑宗总纲，统摄诸卷并承载宗门绝式。',
      perLevelDescription: '限制各基础分卷可研习的最高等级。',
      milestones: [
        {
          id: 'canon-plain',
          level: 1,
          name: '平剑式',
          description: '凌霄弟子的基础剑式。',
          abilityId: 'plain-sword',
        },
        {
          id: 'canon-ultimate',
          level: 70,
          name: '凌霄绝式',
          description: '宗门绝式会随当前流派演化。',
          abilityId: 'sect-ultimate',
        },
      ],
    },
    {
      id: 'sword-guidance',
      slot: 2,
      name: '《御剑纲要》',
      description: '剑宗基础招式总录。',
      perLevelDescription: '每级提高0.05%物理攻击。',
      modifierPerLevel: {
        attrType: AttributeType.ATK,
        type: ModifierType.ADD,
        value: 0.0005,
      },
      milestones: [
        {
          id: 'sword-guiding',
          level: 5,
          name: '引剑式',
          description: '稳定进攻剑式。',
          abilityId: 'guiding-sword',
        },
        {
          id: 'sword-linked',
          level: 10,
          name: '连锋式',
          description: '多段连击剑式。',
          abilityId: 'linked-edge',
        },
      ],
    },
    {
      id: 'void-step',
      slot: 3,
      name: '《凌虚步》',
      description: '身随剑走，主回身与踏影。',
      perLevelDescription: '每级提高0.04%身法。',
      modifierPerLevel: {
        attrType: AttributeType.SPEED,
        type: ModifierType.ADD,
        value: 0.0004,
      },
      milestones: [
        {
          id: 'void-turning',
          level: 15,
          name: '回身式',
          description: '防守反击剑式。',
          abilityId: 'turning-body',
        },
        {
          id: 'void-shadow',
          level: 30,
          name: '踏影',
          description: '攻守转换的身法剑式。',
          abilityId: 'shadow-step',
        },
      ],
    },
    {
      id: 'edge-cleansing',
      slot: 4,
      name: '《洗锋录》',
      description: '洗去剑上滞意，观隙破锋。',
      perLevelDescription: '每级提高0.02个百分点命中。',
      modifierPerLevel: {
        attrType: AttributeType.ACCURACY,
        type: ModifierType.FIXED,
        value: 0.0002,
      },
      milestones: [
        {
          id: 'edge-breaking',
          level: 20,
          name: '破锋式',
          description: '积势后的收束剑式。',
          abilityId: 'breaking-edge',
        },
      ],
    },
    {
      id: 'origin-returning',
      slot: 5,
      name: '《归元诀》',
      description: '敛气归元，以剑罡护体。',
      perLevelDescription: '每级提高0.05%法力上限。',
      modifierPerLevel: {
        attrType: AttributeType.MAX_MP,
        type: ModifierType.ADD,
        value: 0.0005,
      },
      milestones: [
        {
          id: 'origin-aegis',
          level: 20,
          name: '剑罡护体',
          description: '凝聚剑罡护盾。',
          abilityId: 'sword-aegis',
        },
      ],
    },
    {
      id: 'sword-nurturing',
      slot: 6,
      name: '《养剑诀》',
      description: '以气血温养剑意，兼顾恢复与护持。',
      perLevelDescription: '每级提高0.05%气血上限。',
      modifierPerLevel: {
        attrType: AttributeType.MAX_HP,
        type: ModifierType.ADD,
        value: 0.0005,
      },
      milestones: [
        {
          id: 'nurturing-sword',
          level: 20,
          name: '养剑式',
          description: '恢复气血并获得护盾。',
          abilityId: 'nurturing-sword',
        },
      ],
    },
  ],
  abilities: [
    {
      id: 'plain-sword',
      methodId: 'lingxiao-canon',
      baseName: '平剑式',
      description: '默认剑式。',
      unlockLevel: 1,
      occupiesActiveSlot: false,
      role: 'generator',
      manaWeight: 0,
      cooldown: 0,
    },
    {
      id: 'sect-ultimate',
      methodId: 'lingxiao-canon',
      baseName: '凌霄绝式',
      description: '随流派演化的宗门绝式。',
      unlockLevel: 70,
      occupiesActiveSlot: true,
      role: 'finisher',
      manaWeight: 2.5,
      cooldown: 4,
    },
    {
      id: 'guiding-sword',
      methodId: 'sword-guidance',
      baseName: '引剑式',
      description: '低耗的基础进攻剑式。',
      unlockLevel: 5,
      occupiesActiveSlot: true,
      role: 'generator',
      manaWeight: 1,
      cooldown: 0,
    },
    {
      id: 'linked-edge',
      methodId: 'sword-guidance',
      baseName: '连锋式',
      description: '多段连击。',
      unlockLevel: 10,
      occupiesActiveSlot: true,
      role: 'combo',
      manaWeight: 1.5,
      cooldown: 2,
    },
    {
      id: 'turning-body',
      methodId: 'void-step',
      baseName: '回身式',
      description: '进入防守反击姿态。',
      unlockLevel: 15,
      occupiesActiveSlot: true,
      role: 'defensive',
      manaWeight: 1.25,
      cooldown: 3,
    },
    {
      id: 'shadow-step',
      methodId: 'void-step',
      baseName: '踏影',
      description: '攻击并强化下一回合身法。',
      unlockLevel: 30,
      occupiesActiveSlot: true,
      role: 'generator',
      manaWeight: 1,
      cooldown: 2,
    },
    {
      id: 'breaking-edge',
      methodId: 'edge-cleansing',
      baseName: '破锋式',
      description: '消耗积势完成爆发收束。',
      unlockLevel: 20,
      occupiesActiveSlot: true,
      role: 'finisher',
      manaWeight: 1.75,
      cooldown: 2,
    },
    {
      id: 'sword-aegis',
      methodId: 'origin-returning',
      baseName: '剑罡护体',
      description: '凝聚护盾。',
      unlockLevel: 20,
      occupiesActiveSlot: true,
      role: 'defensive',
      manaWeight: 1.5,
      cooldown: 3,
    },
    {
      id: 'nurturing-sword',
      methodId: 'sword-nurturing',
      baseName: '养剑式',
      description: '恢复气血并获得护盾。',
      unlockLevel: 20,
      occupiesActiveSlot: true,
      role: 'utility',
      manaWeight: 1.5,
      cooldown: 4,
    },
  ],
  onboarding: {
    initialContribution: 30,
    initialMethods: { 'lingxiao-canon': 5, 'sword-guidance': 5 },
    initialAbilityLoadout: ['guiding-sword', null, null, null],
  },
};
