import { object } from '@/utils/aiClient';
import {
  getCharacterGenerationPrompt,
  getCharacterGenerationUserPrompt,
} from '@/utils/prompts';
import { z } from 'zod';
import {
  ELEMENT_VALUES,
  GENDER_VALUES,
  REALM_STAGE_VALUES,
  REALM_VALUES,
  SKILL_GRADE_VALUES,
  SKILL_TYPE_VALUES,
  STATUS_EFFECT_VALUES,
} from '../types/constants';
import type {
  CultivationTechnique,
  Cultivator,
  Skill,
} from '../types/cultivator';

const CultivatorSchema = z.object({
  name: z.string().min(2).max(4).describe('2-4字中文姓名'),
  gender: z.enum(GENDER_VALUES).describe('性别'),
  origin: z.string().min(2).max(40).describe('出身势力或地域'),
  personality: z.string().min(2).max(100).describe('性格概述'),
  realm: z.enum(['炼气']).describe('境界'),
  realm_stage: z.enum(REALM_STAGE_VALUES).describe('境界阶段'),
  age: z.number().int().gte(10).lte(100).describe('年龄'),
  lifespan: z.number().int().gte(80).lte(200).describe('寿元'),
  attributes: z
    .object({
      vitality: z.number().int().gte(1).lte(30).describe('体魄'),
      spirit: z.number().int().gte(1).lte(30).describe('灵力'),
      wisdom: z.number().int().gte(1).lte(30).describe('悟性'),
      speed: z.number().int().gte(1).lte(30).describe('身法'),
      willpower: z.number().int().gte(1).lte(30).describe('神识'),
    })
    .describe('基础属性'),
  spiritual_roots: z
    .array(
      z.object({
        element: z.enum(ELEMENT_VALUES).describe('灵根元素'),
        strength: z.number().int().gte(0).lte(95).describe('灵根强度'),
      }),
    )
    .min(1)
    .max(4)
    .describe('灵根'),
  cultivations: z
    .array(
      z.object({
        name: z.string().min(2).max(10).describe('功法名称'),
        grade: z.enum(SKILL_GRADE_VALUES).describe('功法品阶'),
        bonus: z
          .object({
            vitality: z
              .number()
              .int()
              .gte(0)
              .lte(80)
              .optional()
              .describe('体魄增幅'),
            spirit: z
              .number()
              .int()
              .gte(0)
              .lte(80)
              .optional()
              .describe('灵力增幅'),
            wisdom: z
              .number()
              .int()
              .gte(0)
              .lte(80)
              .optional()
              .describe('悟性增幅'),
            speed: z
              .number()
              .int()
              .gte(0)
              .lte(80)
              .optional()
              .describe('身法增幅'),
            willpower: z
              .number()
              .int()
              .gte(0)
              .lte(80)
              .optional()
              .describe('神识增幅'),
          })
          .describe('功法增幅'),
        required_realm: z.enum(REALM_VALUES).describe('境界要求'),
      }),
    )
    .length(2)
    .describe('功法'),
  skills: z
    .array(
      z.object({
        name: z.string().min(2).max(10).describe('神通名称'),
        type: z.enum(SKILL_TYPE_VALUES).describe('神通类型'),
        element: z.enum(ELEMENT_VALUES).describe('神通元素'),
        grade: z.enum(SKILL_GRADE_VALUES).describe('神通品阶'),
        power: z.number().int().gte(0).lte(300).describe('神通威力'),
        cost: z.number().int().gte(0).describe('神通消耗'),
        cooldown: z.number().int().gte(0).describe('神通冷却'),
        effect: z
          .enum(STATUS_EFFECT_VALUES)
          .nullable()
          .optional()
          .describe('神通效果'),
        duration: z.number().nullable().optional().describe('神通持续时间'),
        target_self: z.boolean().optional().describe('施法对象是否为自身'),
      }),
    )
    .min(2)
    .max(3)
    .describe('神通'),
  max_skills: z.number().int().gte(2).lte(6).describe('神通上限'),
  background: z.string().min(10).max(300).describe('背景故事'),
  balance_notes: z.string().max(200).describe('天道平衡性调整说明'),
});

export async function generateCultivatorFromAI(
  userInput: string,
): Promise<{ cultivator: Cultivator; balanceNotes: string }> {
  // 生成 prompt
  const prompt = getCharacterGenerationPrompt();
  const userPrompt = getCharacterGenerationUserPrompt(userInput);

  // 调用 AI 生成角色 Structured Output
  const aiResponse = await object(
    prompt,
    userPrompt,
    {
      schema: CultivatorSchema,
      schemaName: '修仙真形结构',
    },
    false, // use high quality model for character generation
  );

  const generatedData = aiResponse.object;

  // 构造完整的 Cultivator 对象
  const cultivator: Cultivator = {
    ...generatedData,
    id: '', // Placeholder, will be generated by DB
    status: 'active',
    spirit_stones: 0,
    pre_heaven_fates: [], // Generated separately
    inventory: {
      artifacts: [],
      consumables: [],
      materials: [],
    },
    equipped: {
      weapon: null,
      armor: null,
      accessory: null,
    },
    prompt: userInput,
    // Cast explicit types to ensure compatibility
    cultivations: generatedData.cultivations as CultivationTechnique[],
    skills: generatedData.skills as Skill[],
  };

  return {
    cultivator,
    balanceNotes: generatedData.balance_notes,
  };
}
