/** Public spirit-field capabilities. Keep implementation files private. */
export { buildSpiritFruitSpec } from '../spirit-field/spiritFruit.js';
export {
  SPIRIT_FIELD_METHODS,
  SPIRIT_FIELD_METHOD_MAP,
  SPIRIT_FIELD_STARTER_BATCHES,
  advanceSpiritFieldPlotToDecision,
  canPlantSpiritFieldSeed,
  createDefaultSpiritFieldPlots,
  getAffinityScore,
  getCultivationResourceCost,
  getSpiritFieldMarketSeedSlotCount,
  getSpiritFieldMethod,
  getSpiritFieldPlotRuntime,
  getStageDurationMs,
  normalizeSpiritFieldPlots,
  resetSpiritFieldPlot,
  settleSpiritFieldHarvest,
} from '../spirit-field/index.js';
export type {
  SpiritFieldCareAction,
  SpiritFieldCultivationMethod,
  SpiritFieldHarvestSettlement,
  SpiritFieldMethodDefinition,
  SpiritFieldOutcomeKind,
  SpiritFieldPlantSnapshot,
  SpiritFieldPlotRuntimeStatus,
  SpiritFieldPlotState,
  SpiritFieldResourceKind,
  SpiritFieldSeedSpec,
  SpiritFieldStage,
  SpiritFieldStageAffinity,
  SpiritFieldStageHistory,
  SpiritFieldStageJudgment,
  SpiritSeedBatchSpec,
  SpiritSeedGrowthForm,
  SpiritSeedGrowthTrait,
  SpiritSeedHabitatTag,
  SpiritSeedHarvestPart,
  SpiritSeedIdentity,
  SpiritSeedRandomOptions,
  SpiritSeedSkeleton,
  SpiritSeedUseTag,
} from '../spirit-field/index.js';
