/** Public cultivation capabilities. Keep implementation files private. */
export {
  BOTTLENECK_EXP_PENALTY,
  BOTTLENECK_THRESHOLD,
  BREAKTHROUGH_MIN_PROGRESS,
  COMPREHENSION_INSIGHT_CAP,
  DEFAULT_SPIRITUAL_ROOT_STRENGTH,
  EPIPHANY_CHANCE,
  EPIPHANY_EXP_MULTIPLIER,
  EPIPHANY_INSIGHT_MIN,
  EPIPHANY_INSIGHT_RANGE,
  FAILURE_LOSS_PARAMS,
  MAX_NORMAL_INSIGHT,
  NORMAL_BREAKTHROUGH_THRESHOLD,
  NORMAL_INSIGHT_SCALE,
  PERFECT_BREAKTHROUGH_INSIGHT,
  RANDOM_FACTOR_LOW,
  RANDOM_FACTOR_RANGE,
  SPIRITUAL_ROOT_BASE,
  YEARS_MULTIPLIER_BASE,
  YEARS_MULTIPLIER_SCALE,
} from '../cultivation/cultivationTuning.js';
export { EXP_CAP_TABLE } from '../cultivation/cultivationProgress.js';
export {
  BATTLE_VICTORY_EXP_BUDGET,
  DAILY_TASK_EXP_BUDGET,
  DUNGEON_EXP_BUDGET,
  EVENT_EXP_BUDGET,
  OFFLINE_YIELD_EXP_BUDGET,
  REALM_DAILY_EXP_BUDGET,
  RETREAT_EXP_BUDGET,
  SYSTEM_REWARD_EXP_BUDGET,
} from '../cultivation/cultivationExpGain.js';
